<a href="https://colab.research.google.com/github/Chandrani45/MDTS4312_708/blob/main/kmeansclustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
data=load_breast_cancer()

In [4]:
X=pd.DataFrame(data.data)

In [5]:
X.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X.columns=["f"+str(i) for i in range(len(X.columns))]

In [7]:
X.head()

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [8]:
y=data.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [45]:
class KMeans:
  def __init__(self,n_clusters,max_iter):
    self.n_clusters=n_clusters
    self.max_iter=max_iter
    self.centroids=None
  def fit_predict(self,X):
    random_index=np.random.choice(range(0,X.shape[0]),self.n_clusters)
    self.centroids=X.iloc[random_index].values
    for i in range(self.max_iter):
      cluster_group=self.assign_clusters(X)
      old_centroid=self.centroids
      self.centroids=self.move_centroids(X,cluster_group)
      if np.all(old_centroid==self.centroids):
        break
    return cluster_group
  def assign_clusters(self,X):
    cluster_group=[]
    distances=[]
    for row in X.values:
      for centroid in self.centroids:
        distances.append(np.sqrt(np.dot(row-centroid,row-centroid)))
      min_distance=min(distances)
      index_position=distances.index(min_distance)
      cluster_group.append(index_position)
      distances.clear()
    return np.array(cluster_group)
  def move_centroids(self,X,cluster_group):
    new_centroids= []
    cluster_type=np.unique(cluster_group)
    for type in cluster_type:
      new_centroid=np.mean(X.iloc[cluster_group==type].values, axis=0)
      new_centroids.append(new_centroid)
    return np.array(new_centroids)

In [49]:
km=KMeans(3,100)
clusters=km.fit_predict(X)

In [50]:
print(clusters)

[1 1 1 2 1 2 1 0 2 2 0 0 0 0 2 0 0 0 1 2 2 2 0 1 1 0 0 0 0 0 1 2 0 1 0 0 0
 2 2 2 2 2 1 0 2 1 2 2 2 2 2 2 2 0 0 2 1 0 2 2 2 2 0 2 0 0 2 2 2 2 1 2 1 0
 2 0 2 1 1 2 2 2 1 0 2 1 0 1 2 0 0 0 0 2 0 1 2 2 2 0 0 2 2 2 2 2 2 2 1 2 2
 2 2 2 2 2 2 0 0 0 2 1 1 2 2 2 0 1 0 1 2 0 0 0 1 2 2 2 0 2 2 0 2 2 2 2 2 0
 0 2 2 2 2 2 2 2 0 0 2 2 2 1 1 2 1 0 2 0 1 0 2 0 0 2 2 2 2 0 2 2 1 1 0 2 0
 2 0 2 2 2 2 2 2 2 0 2 0 0 1 0 2 0 1 0 2 0 2 0 2 0 1 2 1 0 0 2 2 2 1 1 2 2
 2 0 2 0 2 0 2 2 0 2 2 1 2 2 1 1 2 0 2 2 2 2 0 2 2 2 2 2 1 2 1 0 1 0 1 0 0
 0 1 0 0 0 0 1 2 2 2 2 2 2 1 2 0 2 2 0 2 2 1 2 1 0 2 2 2 2 2 2 0 0 2 2 2 2
 2 2 0 2 1 2 1 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2 1 2 1 2 2 2 2 0 0 0 2 2
 2 2 0 2 1 2 1 0 2 2 1 2 2 2 0 2 2 2 0 1 0 2 2 2 2 2 2 2 2 2 0 2 1 1 2 1 1
 0 0 1 1 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 0 2 2 0 1 2 2 2 2 2 2 0 2 2 2 2 2 0
 2 0 2 2 2 2 0 0 2 2 1 2 2 2 0 2 2 2 2 2 2 2 2 0 2 1 1 0 0 2 2 2 2 2 0 2 2
 0 2 0 0 0 1 2 0 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 2 0 2 2 2 0 2 2 2 0 2 2 0 2
 0 2 2 0 2 0 1 2 0 2 0 0 2 2 0 2 2 1 1 0 2 2 1 2 2 2 2 0 0 2 0 0 0 0 2 0 1
 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 1 2 1 2 2 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 0 1 1 1 0 1 2]

In [54]:
X['clusters']=clusters

In [55]:
X.head(5)

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f21,f22,f23,f24,f25,f26,f27,f28,f29,clusters
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,1
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,1
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,1
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,2
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,1